### ISSUE TITLE
set logout time for local use ?

### ISSUE THREAD

**Issue by zanco** [dernasherbrezon/r2cloud#104]
Hi, Like the software, operating for 2 weeks now, simple antenna but first automatic Meteor-M 2 had nice image !

I would like the webpage not to log me out when I am locally connected to the r2cloud Pi, or extend the time to for example 4 hours.

Is that possible ?

Thanks

**Comment by dernasherbrezon** [comment]
Yes,

 you can override default setting in the ~/.r2cloud config file:

> server.session.timeout.millis=14400000
