### ISSUE TITLE
Nothing from NOAA

### ISSUE THREAD

**Issue by Anjum9694** [dernasherbrezon/r2cloud#107]
Hi it's working for meteor I have received some pictures but there's nothing from NOAA. I had a very high elevation pass with no signal visible on the spectogram.
![Capture](https://user-images.githubusercontent.com/31078090/105202315-a864cb80-5b63-11eb-9a1f-c3946fcccacc.PNG)
![ad](https://user-images.githubusercontent.com/31078090/105202327-ad297f80-5b63-11eb-8b3e-1912d5c36ff9.PNG)

**Comment by dernasherbrezon** [comment]
Closing. Please re-open if it still the case.
