### ISSUE TITLE
Better quality picture

### ISSUE THREAD

**Issue by F21467** [dernasherbrezon/r2cloud#109]
Hello, can we get a better picture for NOAA and if so how? Thank you
![a](https://user-images.githubusercontent.com/84423019/118735889-9eb55100-b841-11eb-8c2f-4acdfb5cbbfe.jpg)

**Comment by Lukas0025** [comment]
it looks like you have a lot of noise in the picture. Better antenna or some filter can help. But with NOAA APT it is necessary to 
count that the images will not be the best, it is an analog transmission. Demonstration of standard quality on https://r2public.eu/observation?ob=319844 If you want good picture look on digital satellites like METEOR-M2 or HRPT of NOAA, but HRPT not supported by R2Cloud yet.

**Comment by F21467** [comment]
Thank you for your answer

**Comment by F21467** [comment]
With a new antenna it's OK
