### ISSUE TITLE
RTL-SDR USB multiple dongles

### ISSUE THREAD

**Issue by Nammurg** [dernasherbrezon/r2cloud#113]
Can we add on the web interface an option for the RTL-SDR USB Serial Number?
I have a setup with one Pi and multiple RTL-SDR USB dongles and I would like for r2cloud to use a specific dongle and not one at random.

**Comment by dernasherbrezon** [comment]
Fixed. Change the local config at ~/.r2cloud. Update the parameter:
```
satellites.rtlsdr.device.index=0
```

By default index is 0.
