### ISSUE TITLE
Duplicate observations 

### ISSUE THREAD

**Issue by ArgoNavi** [dernasherbrezon/r2cloud#127]
Im seeing duplicate observations appear on leosatdata some of which have more frames decoded than whats on r2cloud.

<img width="1124" alt="Screen Shot 2022-09-04 at 6 28 16 PM" src="https://user-images.githubusercontent.com/63644530/188336014-f8207c55-1208-48e4-8ecd-e1b32f0ded7f.png">

<img width="1124" alt="Screen Shot 2022-09-04 at 6 28 39 PM" src="https://user-images.githubusercontent.com/63644530/188336016-c5463a8e-5828-4526-af9c-66dd269d860d.png">

**Comment by dernasherbrezon** [comment]
Most likely was caused by retry on the client side. 

On the server side I added de-duplication based on start time and satellite name. This should solve this issue. Please re-open if occur again.
