### ISSUE TITLE
Meteor-M2

### ISSUE THREAD

**Issue by plato8888** [dernasherbrezon/r2cloud#130]
Please correct the frequency for the Meteor-M2 satellite.  The satellite uses 137.1Mhz for LRPT, not 137.9Mhz.  I need to manually correct the leosatdata.json file every few days to get the r2could service to listen in on the correct frequency to obtain the weather images. 

Thank you.

**Comment by dernasherbrezon** [comment]
Fixed in [855dba0](https://github.com/dernasherbrezon/r2cloud/commit/855dba0bda5c0166524c1bf56bcc620cced3068e)

**Comment by plato8888** [comment]
> Fixed in [855dba0](https://github.com/dernasherbrezon/r2cloud/commit/855dba0bda5c0166524c1bf56bcc620cced3068e)

Thank you!  I'll provide feedback in the next few days to confirm if it corrected the frequency used for future observations.

Take care.
