### ISSUE TITLE
No data decoded, but in fact there is?

### ISSUE THREAD

**Issue by EricFROL** [dernasherbrezon/r2cloud#139]
Hi.
I've set up r2cloud in a rpi, using the image.
Looking at the waterfalls I noticed that there's signal, but r2cloud is not decoding it.
I share here some waterfalls, where no data had been decoded:
https://i.imgur.com/cdx5Mw2.png
https://i.imgur.com/kdFqy7y.png
https://i.imgur.com/wp8PQxG.png
https://i.imgur.com/7c0uy16.png

**Comment by dernasherbrezon** [comment]
Hi,

There are several reasons that can cause that:

- Signal is not strong enough. Even if it is visible on the spectrogram doesn't mean it is decodable. For example the first waterfall has strong signal but also strong interference. 
- Small dynamic range of your rtl-sdr. For example second waterfall has very strong signal on right right that deafens satellite signal.
- Incorrect satellite configuration. This can happen to the newly added satellites when they transmit on unknown baud rates or switched to unknown framing/modulation.
- Bug in r2cloud reception. Some edge-cases from ~50 supported framings/satellites can yield missed frames.

There are several ways to improve that:

- Wait couple of days. Maybe satellite was passing on the very low elevation and your antenna wasn't able to pick it up. More observations required.
- Install band pass filter with LNA right after the antenna. This should reduce interference from FM or other strong sources.
- Select loud satellites such as FUNCUBE-1 or AAUSAT-4
