### ISSUE TITLE
Posssible to run r2cloud on docker?

### ISSUE THREAD

**Issue by Nammurg** [dernasherbrezon/r2cloud#147]
Is it possible to run r2cloud on docker?
I have downloaded the latest docker image from docker hub but I am not able to start it and there is not much documentation about this...
Can you please advise?

**Comment by dernasherbrezon** [comment]
Docker is not officially supported, but it is fairly easy to build one. 

1. Make sure base image is supported version of Debian or Ubuntu
2. Follow the same installation steps as mentioned in the README.md
3. Make sure /tmp directory is properly mapped inside the container.
