### ISSUE TITLE
Configure timezone

### ISSUE THREAD

**Issue by dernasherbrezon** [dernasherbrezon/r2cloud#30]
Separate button to detect using javascript

**Comment by ChadOhman** [comment]
What is the timezone currently set to? I have the raspberry pi set to UTC-7 but my passes predicted via Orbitron do not match with what r2cloud is reporting.
![2020-01-16 21_06_58-r2cloud](https://user-images.githubusercontent.com/2351/72583626-2ed93400-38a4-11ea-8d1b-7eb3d1acc8c8.png)
![2020-01-16 21_07_05-Orbitron 3 71](https://user-images.githubusercontent.com/2351/72583627-2ed93400-38a4-11ea-926b-fa413d492e24.png)

Thanks

**Comment by dernasherbrezon** [comment]
r2cloud has min and guaranteed elevation limits while calculating passes. Default values are:

- min = 8
- guaranteed = 20

That means any passes without elevation < 20 are not considered. Also observations starts/ends at 8 degrees of elevation.

Regarding your example, what is the timezone for "Time - LOC" ? What is "Elv" (is it max, or initial or)?

**Comment by ChadOhman** [comment]
LOC is UTC-7 and Elv is max.

Thanks for your insight.

**Comment by dernasherbrezon** [comment]
Yes, Looks like orbitron "NOAA 19 2020-01-17 05:32:39" matches r2cloud on 12:27. 5 minute difference might arise from:

1. stale TLE in r2cloud
2. min elevation in r2cloud > min elevation in orbitron.
