### ISSUE TITLE
Generate spectrogram of weather satellite signals

### ISSUE THREAD

**Issue by dernasherbrezon** [dernasherbrezon/r2cloud#34]
Will help with debugging

**Comment by zeroby0** [comment]
Hi! Can you zoom in the spectrogram to the center frequency? Currently it's multiple MHz wide, so the actual signal is just a thin line.

**Comment by dernasherbrezon** [comment]
Do you have an example? Currently it is 240khz or 288khz wide. And you can't "zoom" because FFT was created once and all buckets are pixels. So if you want to zoom into the part of the spectrogram, you have to define smaller FFT bucket and run FFT on the original data.

**Comment by zeroby0** [comment]
Here is a spectrogram for a NOAA 18 pass.

I thought the thin line in the center is the NOAA transmission, but if the current width is 240Khz, then the 40KHz NOAA signal is too thin to be the thin center line. If the width is 240Khz, then there is no need to zoom in more. 

But isn't this spectrogram too symmetric? That's a bit suspicious, do you know what's going on here?

![spectogram-1](https://user-images.githubusercontent.com/16903044/87464362-9e9c6180-c630-11ea-9308-3e66f1547782.png)

**Comment by dernasherbrezon** [comment]
Hey, couple of things:

1. The line right in the middle is [dc offset](https://en.wikipedia.org/wiki/DC_bias).
2. The actual signal is within thick lines on both sides. It doesn't have clear APT spikes like here, because of small spectrogram resolution.

![](https://www.rtl-sdr.com/wp-content/uploads/2013/05/NOAA_APT_Zoom.png)

3. They are symmetric because NOAA signals are fm demodulated and stored in .wav file. They don't have imaginary part, thus symmetric after FFT.

**Comment by zeroby0** [comment]
If they are symmetric, can we drop one half so we can have a better use of space? Maybe also a smaller spectral width for NOAA satellites so we can see it better?
