### ISSUE TITLE
Connect 2 dongles or 2 PI's?

### ISSUE THREAD

**Issue by jeffreypkelly** [dernasherbrezon/r2cloud#57]
Since some of the satellites are on 137 and others are on 435, I would like to use two antennas.
Can I connect two rtlsdr dongles - one for 137 and one for 435? Or should I run two PI systems
and just check the 137 satellites on one pi and the 435 satellites on the other pi?

**Comment by jeffreypkelly** [comment]
Cancel - must have had an extra space at end of keyword - all good.

**Comment by dernasherbrezon** [comment]
Better run 2 pi. This will organically double the CPU power + 2 schedulers can track 2 satellites concurrently.
