### ISSUE TITLE
I am connected and running but not seeing any files saved.

### ISSUE THREAD

**Issue by jeffreypkelly** [dernasherbrezon/r2cloud#58]
Any suggestions?  I have an rtlsdr feed by a 137 mhz QFH antenna.
Where are files stored locally? How can I trouble shoot?

![Screen Shot 2019-10-26 at 9 49 40 AM](https://user-images.githubusercontent.com/34376383/67620548-14784880-f7d6-11e9-8a45-c3d7e3a74d2e.png)

**Comment by dernasherbrezon** [comment]
Hi! You can click on observation and check spectogram. Also, logs are available in journald:

> journalctl -u r2cloud -n 200

**Comment by jeffreypkelly** [comment]
In the log I am getting the usb_claim_interface error -6 error message.

When I reboot and run rtf_test or a FM radio command:
"rtl_fm -g 50 -f 95.9M -M wfm -s 180k -E deemp |  play -r 180k -t raw -e s -b 16 -c 1 -V1 - lowpass 16k” 
everything works well.

Do I have a permissions issue?

Jeff

**Comment by dernasherbrezon** [comment]
Maybe. Can you:
1) Check if no other software is using RTL-SDR
2) Check if kernel driver loaded first: lsmod |grep rtl ( See some remediation here https://stackoverflow.com/questions/43879570/usb-claim-interface-error-6-on-rtl-sdr)

**Comment by jeffreypkelly** [comment]
> On Oct 26, 2019, at 3:54 PM, dernasherbrezon <notifications@github.com> wrote:
> 
> Maybe. Can you:
> 
> Check if no other software is using RTL-SDR
I am using your image and no other software installed.
> Check if kernel driver loaded first: lsmod |grep rtl ( See some remediation here https://stackoverflow.com/questions/43879570/usb-claim-interface-error-6-on-rtl-sdr <https://stackoverflow.com/questions/43879570/usb-claim-interface-error-6-on-rtl-sdr>)
No results with this grep

I have the modprobe.d blacklist files in.

It is funny that I can run rtl_test and a rtl_fm command and not have an error.

OK I’ll mess around.  Is there a way to manually start a recording for r2cloud so I can test manually?

Jeff

**Comment by dernasherbrezon** [comment]
There are 2 options:
1) Check the logs for the actual command. It should output something like: ```./etc/rtl_sdr_wrapper.sh -rtl rtl_sdr -f ...```. You can run this command manually
2) REST API. Authenticate using REST API and execute immediate observation. See https://github.com/dernasherbrezon/r2cloud/blob/master/src/test/java/ru/r2cloud/it/ObservationTest.java for code example.

**Comment by jeffreypkelly** [comment]
OK I got into HTOP and killed the pid for rtf that was running and low and behold this shows up from NOAA 19:
So let me monitor this and see if somehow the rtl_fm is not shutting down and thus preventing a restart on the next pass.

TY!

Jeff

**Comment by jeffreypkelly** [comment]
Things seem to be working so you can close, delete this.
TY!

Jeff

**Comment by jeffreypkelly** [comment]
Can I find my api key on the sd card?

Jeff

**Comment by jeffreypkelly** [comment]
Cancel, created account.

Jeff
