### ISSUE TITLE
Session time from local r2cloud is too short

### ISSUE THREAD

**Issue by DE8MSH** [dernasherbrezon/r2cloud#69]
Hey.

The session time from the local r2cloud is too short. After 2-3 minutes I have to reenter the name and pw. This is too short for maken any changes, scheduling etc. p. p.

73

**Comment by dernasherbrezon** [comment]
Yes, makes sense. Increased to 30 minutes

**Comment by DE8MSH** [comment]
You can reopen this issue. I talked about LOCAL session time. Still only 1-3 minutes.

**Comment by dernasherbrezon** [comment]
Can you check parameter ```server.session.timeout.millis``` in the /home/pi/r2cloud/etc/config-prod.properties ?

**Comment by DE8MSH** [comment]
360000. So 6 minutes. I'll set it up to a longer timeout time. Thanks.

**Comment by dernasherbrezon** [comment]
Yes, currently it is:

#30 minutes
server.session.timeout.millis=1800000

You can simply turn on automatic updates to get all new stuff daily.

**Comment by DE8MSH** [comment]
Thanks. Now you can close this issue.

But the other issue (cannot reset passwort) is still open and most important!!! Help me with it, please. Thank you.
