### ISSUE TITLE
Missing uploads

### ISSUE THREAD

**Issue by chris-y** [dernasherbrezon/r2cloud#71]
I've seen this a couple of times now, but r2cloud sometimes misses uploading observations. Overnight I had no uploads between 2035 and 0902.
![Point Blur_Dec072019_175954](https://user-images.githubusercontent.com/1818803/70378705-6a82f480-191b-11ea-92b8-a4fde7df6142.jpg)

![Point Blur_Dec072019_175417](https://user-images.githubusercontent.com/1818803/70378669-16781000-191b-11ea-84b1-09aa106f233d.jpg)

**Comment by dernasherbrezon** [comment]
Yes, there was an issue with r2server. Right now should be ok.
