### ISSUE TITLE
SDR-USB Dongle gain and ppm settings

### ISSUE THREAD

**Issue by Whimick** [dernasherbrezon/r2cloud#75]
Please could you add the option to set the ppm and gain for SRD-USB dongles.

**Comment by dernasherbrezon** [comment]
Gain can be configured at:

~/.r2cloud

```
satellites.rtlsdr.gain=45
```

**Comment by dernasherbrezon** [comment]
Now available in the "general" settings. By default PPM type is AUTO. But could be MANUAL with the integer PPM value.
