### ISSUE TITLE
Please add Meteor M2-2

### ISSUE THREAD

**Issue by errolt** [dernasherbrezon/r2cloud#76]
Please add Meteor M2-2 to the list of satellites. 

I tried to add it to the config file, but r2cloud ignores the source=LRPT config line and does not know how to decode Meteor M2-2. The decoding method seems to be hard-coded for each supported satellite.

**Comment by dernasherbrezon** [comment]
Yes, Meteor M2-2 decoder differs from Meteor M2. I used to support it, but after the failure Meteor M2-2 is no longer transmitting on 137Mhz. So I completely removed it.

**Comment by errolt** [comment]
Ahh, sorry. I saw about accident, but only saw note that damage was still being assessed. Did not know 137MHz transmitter is dead.
