### ISSUE TITLE
Schedule Tab  order - Rtl_fm options - Time set

### ISSUE THREAD

**Issue by iu0azb** [dernasherbrezon/r2cloud#80]
Hope it's ok to summarize my consideration as single issue:)

- Would be useful choose order the schedule by time or satellite name. 

- Another useful add would be modify/view from web page  rtl_fm parameters, like agc mode, gain etc.. this to optimize frontend easily... Here the Bias control option can simplify the user actions.

- I didn't find noted to set the system to UTC time. Because not reported Timezone on web interface, if incorrectly set, system can start all receptions at wrong time.
 
Thanks, Luca

**Comment by dernasherbrezon** [comment]
Fixed sort by satellite name and next pass time.

**Comment by iu0azb** [comment]
Great! it's now easier to verified incoming sats.

**Comment by dernasherbrezon** [comment]
I added server time to the overview page. Most of the issues with observations related to the incorrectly configured server time. raspberry pi by default doesn't have realtime clock. So working without internet connection ( and NTP ) could trigger lots of strange issues. 

![Screen Shot 2020-07-14 at 9 39 43 PM](https://user-images.githubusercontent.com/1614424/87474175-9afde000-c61a-11ea-86ea-d0b8bc682cea.png)

gain and bias-t settings will be handled in #89
