### ISSUE TITLE
Unable to finish the setup wizard

### ISSUE THREAD

**Issue by javajox** [dernasherbrezon/r2cloud#90]
I'm trying to install r2cloud using installation procedure when Raspberrypi is my own (not a pre-build image with r2cloud), so I performed these steps :

sudo apt-get install dirmngr
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A5A70917
sudo bash -c "echo 'deb [arch=armhf] http://s3.amazonaws.com/r2cloud r2cloud main' > /etc/apt/sources.list.d/r2cloud.list"
sudo apt-get update
sudo apt-get install r2cloud

Next I accessed the Raspberrypi and followed the wizard, in the end (at the "Automatic updates") step when I press "Finish" button, nothing is happening. Here are the last log records from systemd :

Jul 23 17:00:11 raspberrypi java[397]: unable to save: {gain=Cannot be empty} [ru.r2cloud.web.api.configuration.General doPost]
Jul 23 16:59:13 raspberrypi systemd[1]: Started Session c1 of user pi.
Jul 23 16:59:13 raspberrypi systemd[1]: Started User Manager for UID 1000.
Jul 23 16:59:13 raspberrypi systemd[435]: Startup finished in 398ms.
Jul 23 16:59:13 raspberrypi systemd[435]: Reached target Default.
Jul 23 16:59:13 raspberrypi systemd[435]: Reached target Basic System.
Jul 23 16:59:13 raspberrypi systemd[435]: Reached target Sockets.
Jul 23 16:59:13 raspberrypi systemd[435]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Jul 23 16:59:13 raspberrypi systemd[435]: Reached target Timers.
Jul 23 16:59:13 raspberrypi systemd[435]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Jul 23 16:59:13 raspberrypi systemd[435]: Reached target Paths.
Jul 23 16:59:13 raspberrypi systemd[435]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jul 23 16:59:13 raspberrypi systemd[435]: Listening on GnuPG network certificate management daemon.
Jul 23 16:59:13 raspberrypi systemd[435]: Listening on GnuPG cryptographic agent and passphrase cache.
Jul 23 16:59:12 raspberrypi systemd[435]: pam_unix(systemd-user:session): session opened for user pi by (uid=0)
Jul 23 16:59:12 raspberrypi systemd[1]: Starting User Manager for UID 1000...
Jul 23 16:59:12 raspberrypi systemd[1]: Started User Runtime Directory /run/user/1000.
Jul 23 16:59:12 raspberrypi systemd-logind[280]: New session c1 of user pi.
Jul 23 16:59:12 raspberrypi systemd[1]: Starting User Runtime Directory /run/user/1000...
Jul 23 16:59:12 raspberrypi systemd[1]: Created slice User Slice of UID 1000.
Jul 23 16:59:12 raspberrypi sshd[427]: pam_unix(sshd:session): session opened for user pi by (uid=0)
Jul 23 16:59:12 raspberrypi sshd[427]: Accepted password for pi from 10.10.10.12 port 59248 ssh2
Jul 23 16:58:30 raspberrypi systemd[1]: Startup finished in 3.007s (kernel) + 1min 32.033s (userspace) = 1min 35.041s.
Jul 23 16:58:30 raspberrypi systemd[1]: Started Update UTMP about System Runlevel Changes.
Jul 23 16:58:30 raspberrypi systemd[1]: systemd-update-utmp-runlevel.service: Succeeded.
Jul 23 16:58:30 raspberrypi systemd[1]: Starting Update UTMP about System Runlevel Changes...
Jul 23 16:58:30 raspberrypi systemd[1]: Reached target Graphical Interface.
Jul 23 16:58:30 raspberrypi systemd[1]: Reached target Multi-User System.
Jul 23 16:58:30 raspberrypi systemd[1]: dev-serial1.device: Job dev-serial1.device/start failed with result 'timeout'.
Jul 23 16:58:30 raspberrypi systemd[1]: hciuart.service: Job hciuart.service/start failed with result 'dependency'.
Jul 23 16:58:30 raspberrypi systemd[1]: Dependency failed for Configure Bluetooth Modems connected by UART.
Jul 23 16:58:30 raspberrypi systemd[1]: Timed out waiting for device /dev/serial1.
Jul 23 16:58:30 raspberrypi systemd[1]: dev-serial1.device: Job dev-serial1.device/start timed out.
Jul 23 16:57:38 raspberrypi java[397]: ================================= [ru.r2cloud.R2Cloud start]
Jul 23 16:57:38 raspberrypi java[397]: =========== started ============= [ru.r2cloud.R2Cloud start]
Jul 23 16:57:38 raspberrypi java[397]: ================================= [ru.r2cloud.R2Cloud start]
Jul 23 16:57:38 raspberrypi java[397]: webserver is listening on localhost:8097 [ru.r2cloud.web.WebServer start]
Jul 23 16:57:38 raspberrypi java[397]: metrics started [ru.r2cloud.metrics.Metrics start]
Jul 23 16:57:37 raspberrypi java[397]: SIGAR library was loaded [ru.r2cloud.metrics.Metrics start]
Jul 23 16:57:37 raspberrypi java[397]: CPU count: 4 [ru.r2cloud.metrics.Metrics start]
Jul 23 16:57:37 raspberrypi java[397]: total memory: 16252928 [ru.r2cloud.metrics.Metrics start]
Jul 23 16:57:37 raspberrypi java[397]: max memory: 235274240 [ru.r2cloud.metrics.Metrics start]
Jul 23 16:57:37 raspberrypi java[397]: started [ru.r2cloud.satellite.Scheduler start]
Jul 23 16:57:37 raspberrypi java[397]: rotator is disabled [ru.r2cloud.satellite.RotatorService start]
Jul 23 16:57:37 raspberrypi java[397]: next tle update at: Sat Jul 25 00:00:00 UTC 2020 [ru.r2cloud.tle.TLEReloader start]
Jul 23 16:57:37 raspberrypi java[397]: started [ru.r2cloud.RtlSdrStatusDao start]
Jul 23 16:57:37 raspberrypi java[397]: schedule ppm auto update. next execution at: Fri Jul 24 00:00:00 UTC 2020 [ru.r2cloud.RtlSdrStatusDao scheduleAutoPpm]
Jul 23 16:57:37 raspberrypi java[397]: ddns is disabled [ru.r2cloud.ddns.DDNSClient start]
Jul 23 16:57:36 raspberrypi systemd-timesyncd[232]: Synchronized to time server for the first time 31.131.0.123:123 (2.debian.pool.ntp.org).
Jul 23 16:57:23 raspberrypi systemd[1]: systemd-fsckd.service: Succeeded.

Any idea ? Or I can provide more data if needed

**Comment by dernasherbrezon** [comment]
The root cause:

> unable to save: {gain=Cannot be empty}

Fixed. Try running sudo apt-get install r2cloud-ui and restart r2cloud afterwards.
