### ISSUE TITLE
 17/5000 No NOAA pictures

### ISSUE THREAD

**Issue by EA4GSX** [dernasherbrezon/r2cloud#95]
Hello
I really like the project, it is very interesting but I have several problems. With the same configuration in windows I can decode more frames. Nor can I receive images from the meteorological satellites. Could it be the saturation of the LNA?
Thanks in advance and congratulations on the project
![Captura](https://user-images.githubusercontent.com/63553394/93721992-e3de9180-fb93-11ea-95b2-0f44fe1f7e86.PNG)

**Comment by dernasherbrezon** [comment]
Hey,

Yes, it could be. Or antenna was not connected to the rtl-sdr. I cannot see anything on the spectrogram.

**Comment by EA4GSX** [comment]
Hello again
The antenna was connected  with NOAA you don't see a signal but with the rest you can see a lot of the Doppler. This is normal?
![Captura2](https://user-images.githubusercontent.com/63553394/93762144-4f197980-fc0f-11ea-8212-b0ec11ea92af.PNG)

**Comment by dernasherbrezon** [comment]
Hi! Yes, spectrogram contains the visualization of raw i/q data (.wav file) before applying any corrections to the data.

**Comment by EA4GSX** [comment]
Okay
Thank you very much for your help, finally, why could the problem be with the noaa? with the METEOR if I see a signal in the waterfall

Thank you

**Comment by dernasherbrezon** [comment]
> why could the problem be with the noaa? 

Do you see the same picture for all NOAA satellites or just one pass had it?

**Comment by EA4GSX** [comment]
Hello
The problem is with all NOAA passes
